### PR TITLE
Fix Missing exports condition

### PR DESCRIPTION
**Pull request by nmontavon**
Fix the Missing Export Condition Error caused by Vite deprecating support without it in the future.

Info:  https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

relates to issue https://github.com/Brisklemonade/radix-icons-svelte/issues/1

### CODE REVIEW

**Review by niemyjski — APPROVED** [review]

**Comment by niemyjski** [comment]
Pr looks good

**Comment by bartvdbraak** [comment]
Hi @Brisklemonade, is it possible to merge this PR or are there any other issues preventing it?

**Comment by shiftlabs1** [comment]
@Brisklemonade  please merge this PR in. This is the only lib in our application that is not yet compliant . Please

**Comment by skyfallwastaken** [comment]
@vyconm The version should be bumped to 1.2.1 I'm pretty sure

**Comment by telesvar** [comment]
Hello, everyone. As this package, unfortunately, is not well maintained, I put an effort to create an alternative: https://github.com/furtuna-digital/radix-icons-svelte

P.S., this uses Svelte 5 and does not work with Svelte 4 but I can create a branch compatible with Svelte 4 if anyone asks.

**Comment by kamellperry** [comment]
merged

**Pull request merged**
